In [97]:
import scipy.io
import numpy as np
np.random.seed(seed=37)
# Training data 
mat = scipy.io.loadmat('test_data/ex4data1.mat')
arrays = {}

for k, v in mat.items():
    arrays[k] = np.array(v)
X = arrays['X']
y_ = arrays['y']
y_[y_ == 10] = 0

y = np.zeros((np.size(y_),10))
for i in range(np.size(y_)):
    y[i,y_[i] ] = 1
idx = np.random.randint(0,4999,10)
# print(idx)
print(y[idx,:])
print(y_[idx,:])



[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[3]
 [8]
 [1]
 [1]
 [9]
 [8]
 [7]
 [7]
 [9]
 [1]]


In [59]:
# Weights data 
mat = scipy.io.loadmat('test_data/ex4weights.mat')
arrays = {}
for k, v in mat.items():
    arrays[k] = np.array(v)
Theta0 = arrays['Theta1']
Theta1 = arrays['Theta2']

print(np.shape(Theta0))
print(np.shape(Theta1))


(25, 401)
(10, 26)


In [72]:
from network import Sequential

model = Sequential([400,25,10])
model.weights[0][:,:] = Theta0
model.weights[1][:,:] = Theta1


In [4]:
def costfunc(y,y_pred):
    n_samples = np.shape(y)[0]
    cost = 0
    for isp in range(n_samples):
            cost += -np.dot(y[isp,:],np.log(y_pred[isp,:])) - np.dot((1 - y[isp,:]),np.log(1 - y_pred[isp,:]))
    return 1/n_samples * cost 


In [27]:
# Test cost function and forward propagation
from network import Sequential
import numpy as np
model = Sequential([2,2,4])
X = np.cos([[1, 2], [3, 4] , [5,6]])
y =  np.array([ [0., 0., 0., 1],
                [0., 1., 0., 0.],
                [0., 0., 1., 0.] ]) # = np.array([4,2,3])

# print(np.shape(model.weights[1])) 
params = np.arange(1,19)/10
model.weights[0][:,:] = np.reshape(params[0:6],(2,3),'F')
model.weights[1][:,:] =  np.reshape(params[6:18],(4,3),'F')
y_pred = model.propagate_forward(X[0])
print(np.shape(y_pred))
y_pred = np.array(list(map(model.propagate_forward,X)))
print(np.shape(y_pred))
print(model.layers_b[1])






(4,)
(3, 4)
[0.22426417 0.20640222]


In [2]:
# Test cost function and forward propagation
from network import Sequential, costfunc, regularization_term
import numpy as np
X = np.cos([[1, 2], [3, 4] , [5,6]])
y =  np.array([ [0., 0., 0., 1],
                [0., 1., 0., 0.],
                [0., 0., 1., 0.] ]) # = np.array([4,2,3])

# print(np.shape(model.weights[1])) 
params = np.arange(1, 19) / 10
weights = [ np.reshape(params[0:6], (2, 3), "F"),np.reshape(params[6:18], (4, 3), "F") ]
model = Sequential([2, 2, 4],weights)
y_pred = np.array(list(map(model.propagate_forward,X)))

accum = np.zeros((2,3))
y_pred = np.zeros(np.shape(y))
cost = np.zeros(1)
reg_par = 4
for i in range(3):
    y_pred[i] = model.propagate_forward(X[i])
    model.propagate_backward(y_pred[i] - y[i] ) 
    accum += model.accumulators[-2]
    cost += costfunc(y[i],y_pred[i])

model.make_gradients(reg_par,len(y))
reg = regularization_term(weights,reg_par)
cost += reg
cost /= len(y)

model.gradients[-2]


array([[0.76613837, 0.37246038, 0.64173788],
       [0.97989687, 0.49748912, 0.74613831]])

In [9]:
a = np.array([0.76614,
0.97990,
0.37246,
0.49749,
0.64174,
0.74614,
0.88342,
0.56876,
0.58467,
0.59814,
1.92598,
1.94462,
1.98965,
2.17855,
2.47834,
2.50225,
2.52644,
2.72233])
b = np.reshape(a[6:],(4,3) ,"F")
b

array([[0.88342, 1.92598, 2.47834],
       [0.56876, 1.94462, 2.50225],
       [0.58467, 1.98965, 2.52644],
       [0.59814, 2.17855, 2.72233]])