In [97]:
import scipy.io
import numpy as np
np.random.seed(seed=37)
# Training data 
mat = scipy.io.loadmat('test_data/ex4data1.mat')
arrays = {}

for k, v in mat.items():
    arrays[k] = np.array(v)
X = arrays['X']
y_ = arrays['y']
y_[y_ == 10] = 0

y = np.zeros((np.size(y_),10))
for i in range(np.size(y_)):
    y[i,y_[i] ] = 1
idx = np.random.randint(0,4999,10)
# print(idx)
print(y[idx,:])
print(y_[idx,:])



[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[3]
 [8]
 [1]
 [1]
 [9]
 [8]
 [7]
 [7]
 [9]
 [1]]


In [59]:
# Weights data 
mat = scipy.io.loadmat('test_data/ex4weights.mat')
arrays = {}
for k, v in mat.items():
    arrays[k] = np.array(v)
Theta0 = arrays['Theta1']
Theta1 = arrays['Theta2']

print(np.shape(Theta0))
print(np.shape(Theta1))


(25, 401)
(10, 26)


In [72]:
from network import Sequential

model = Sequential([400,25,10])
model.weights[0][:,:] = Theta0
model.weights[1][:,:] = Theta1


In [4]:
def costfunc(y,y_pred):
    n_samples = np.shape(y)[0]
    cost = 0
    for isp in range(n_samples):
            cost += -np.dot(y[isp,:],np.log(y_pred[isp,:])) - np.dot((1 - y[isp,:]),np.log(1 - y_pred[isp,:]))
    return 1/n_samples * cost 


In [27]:
# Test cost function and forward propagation
from network import Sequential
import numpy as np
model = Sequential([2,2,4])
X = np.cos([[1, 2], [3, 4] , [5,6]])
y =  np.array([ [0., 0., 0., 1],
                [0., 1., 0., 0.],
                [0., 0., 1., 0.] ]) # = np.array([4,2,3])

# print(np.shape(model.weights[1])) 
params = np.arange(1,19)/10
model.weights[0][:,:] = np.reshape(params[0:6],(2,3),'F')
model.weights[1][:,:] =  np.reshape(params[6:18],(4,3),'F')
y_pred = model.propagate_forward(X[0])
print(np.shape(y_pred))
y_pred = np.array(list(map(model.propagate_forward,X)))
print(np.shape(y_pred))
print(model.layers_b[1])






(4,)
(3, 4)
[0.22426417 0.20640222]


In [2]:
# Test cost function and forward propagation
from network import Sequential
import numpy as np
X = np.cos([[1, 2], [3, 4] , [5,6]])
y =  np.array([ [0., 0., 0., 1],
                [0., 1., 0., 0.],
                [0., 0., 1., 0.] ]) # = np.array([4,2,3])

# print(np.shape(model.weights[1])) 
params = np.arange(1, 19) / 10
weights = [ np.reshape(params[0:6], (2, 3), "F"),np.reshape(params[6:18], (4, 3), "F") ]
model = Sequential([2, 2, 4],weights)
y_pred = np.array(list(map(model.propagate_forward,X)))

accum = np.zeros((2,3))
y_pred = np.zeros(np.shape(y))
for i in range(3):
    y_pred[i] = model.propagate_forward(X[i])
    model.propagate_backward(y_pred[i] - y[i] ) 
    accum += model.accumulators[-2]
model.accumulators[-1]/3


array([[0.88341721, 0.45931355, 0.47833662],
       [0.56876234, 0.34461818, 0.36892041],
       [0.58466766, 0.25631333, 0.25977062],
       [0.59813924, 0.31188506, 0.32233089]])

7.406969856065747