In [2]:
import scipy.io
import numpy as np
import matplotlib.pyplot as plt
from network import Sequential, costfunc, regularization_term, output_class
from sklearn.model_selection import train_test_split

In [3]:
# Weights data 
mat = scipy.io.loadmat('test_data/ex4weights.mat')
arrays = {}
for k, v in mat.items():
    arrays[k] = np.array(v)
Theta0 = arrays['Theta1']
Theta1 = arrays['Theta2']

print(np.shape(Theta0))
print(np.shape(Theta1))

(25, 401)
(10, 26)


In [7]:
np.random.seed(seed=37)
# Training data 
mat = scipy.io.loadmat('test_data/ex4data1.mat')
arrays = {}

for k, v in mat.items():
    arrays[k] = np.array(v)
X = arrays['X']
y_ = arrays['y']
y_[y_ == 10] = 0

y = np.zeros((np.size(y_),10))
for i in range(np.size(y_)):
    y[i,y_[i] ] = 1
idx = np.random.randint(0,4999,10)
# print(idx)
print(y[idx,:])
print(y_[idx,:])

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[3]
 [8]
 [1]
 [1]
 [9]
 [8]
 [7]
 [7]
 [9]
 [1]]


In [8]:

# Random weights
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
layer_dims = [400, 25, 10]
eps_init = 0.12
weights= [
            np.random.uniform(-eps_init, eps_init, (layer_dims[i + 1], layer_dims[i] + 1))
            for i in range(len(layer_dims) -1)
        ]
model = Sequential(layer_dims, weights)
alpha = .1 # Regularization parameter
n_epochs = 50
batch_size = len(y_train)

for ie in range(n_epochs):
    eta =   1.0 - 0.9*ie/n_epochs # Learning rate

    model.zero_gradients()
    y_pred = np.array(list(map(model, X_train, y_train)))
    y_out = np.array(list(map(output_class,y_pred)))
    model.make_gradients(alpha, batch_size)
    scores = [np.allclose(youti,yi) for youti, yi in zip(y_out,y_train)]
    accuracy = sum(scores)/batch_size
    cost = sum(costfunc(yi, y_predi) for yi, y_predi in zip(y_train, y_pred))
    reg_term = regularization_term(model.weights, alpha)
    cost += reg_term
    cost /= batch_size

    for i in range(model.n_weights):
        model.weights[i] -= eta*model.gradients[i] 

    if ie % 1 == 0:
        print(f"step {ie} cost {cost}, accuracy {accuracy*100}%")

step 0 cost 6.745929024077091, accuracy 10.24%
step 1 cost 3.4348508272822458, accuracy 10.6%
step 2 cost 3.243494947369233, accuracy 10.68%
step 3 cost 3.230587236437102, accuracy 12.520000000000001%
step 4 cost 3.2219514389356556, accuracy 15.76%
step 5 cost 3.2137473296145673, accuracy 24.240000000000002%
step 6 cost 3.205366725279811, accuracy 31.72%
step 7 cost 3.1966069798317136, accuracy 36.480000000000004%
step 8 cost 3.1873640295765004, accuracy 40.36%
step 9 cost 3.1775665786346, accuracy 43.120000000000005%
step 10 cost 3.1671589597045404, accuracy 46.12%
step 11 cost 3.1560967865552074, accuracy 48.44%
step 12 cost 3.144346150317429, accuracy 50.63999999999999%
step 13 cost 3.131883830777094, accuracy 52.2%
step 14 cost 3.1186977725083858, accuracy 54.08%
step 15 cost 3.104787553871284, accuracy 55.60000000000001%
step 16 cost 3.0901647115843285, accuracy 56.720000000000006%
step 17 cost 3.0748528308167353, accuracy 57.76%
step 18 cost 3.058887339438824, accuracy 59.08%
ste